# Generated by Django 3.1.5 on 2022-01-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('arriving', 'arriving'), ('arrived', 'arrived')], max_length=200)),
            ],
        ),
    ]
